name: "Monthly Security Scan"

on:
  push:
    branches:
      - 'security-testing'
      - 'security**'
      
  workflow_dispatch:
    inputs:
      logMessage:
        description: 'Github Monthly Scan Security'
        required: false
        default: ''

jobs:
  scan_source_code:
    name: Scanner Dependency Check 
    uses: MTI-Advanced-Tec-Dept/ci-workflow-templates/.github/workflows/dependency_check.yml@security-testing
    with:
      scan-path: '.'

  upload-reports-to-gcs:
    name: Upload Reports to GCS
    needs: [scan_source_code]
    if: always()
    uses: MTI-Advanced-Tec-Dept/ci-workflow-templates/.github/workflows/upload-artifact-to-gcs.yml@security-testing
    with:
      gcp_project_id: 'one-global-dilab-sandbox-dev'
      gcs_bucket: 'ghq-diai-prod-security-reports'
      defectdojo_url: ${{ vars.DOJO_URL }}
      api_token: ${{ secrets.DOJO_API_TOKEN }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_ONE_GLOBAL_DILAB_SANDBOX_DEV }}
